import { TokenCompilerError } from "./token-compiler.mjs";

/** Named layout container on `.cu-app-shell` — not a new token prefix. */
export const APP_SHELL_CONTAINER = "app-shell";

function requireToken(compiled, name) {
  const token = compiled.tokens.find((entry) => entry.path.join(".") === name);
  if (!token) {
    throw new TokenCompilerError(
      name,
      "a Phase 5 token required by the density layer is missing",
      `add ${name} to src/core/*.json and rerun the token build`,
    );
  }
  return token.value;
}

function cssLength(value) {
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && typeof value.value === "number") {
    return `${value.value}${value.unit}`;
  }
  throw new TokenCompilerError(
    "density.css",
    `expected a resolved dimension, got ${JSON.stringify(value)}`,
    "keep breakpoint/control-size tokens as DTCG dimension objects",
  );
}

function belowRem(tokenValue) {
  const { value, unit } = tokenValue;
  if (unit !== "rem" || typeof value !== "number") {
    throw new TokenCompilerError(
      "breakpoint",
      `expected a rem dimension, got ${JSON.stringify(tokenValue)}`,
      "express breakpoints in rem so zoom stays correct",
    );
  }
  return `${(value - 0.01).toFixed(2)}rem`;
}

/**
 * Phase 5 density layer: default density per frozen breakpoint plus the
 * [data-density] opt-out. Viewport @media covers page-level shells; named
 * `@container app-shell` covers a narrow shell inside a wide viewport (A5.3).
 *
 * @complexity time O(1) | space O(1) | fixed token set
 * @guarantees deterministic; no timestamps; values come only from compiled tokens
 */
export function renderDensityCss(compiled) {
  const tablet = requireToken(compiled, "breakpoint.tablet");
  const desktop = requireToken(compiled, "breakpoint.desktop");
  const scale = {
    compact: requireToken(compiled, "density.compact"),
    standard: requireToken(compiled, "density.standard"),
    comfortable: requireToken(compiled, "density.comfortable"),
  };
  const size = {
    compact: cssLength(requireToken(compiled, "control.size.compact")),
    standard: cssLength(requireToken(compiled, "control.size.standard")),
    comfortable: cssLength(requireToken(compiled, "control.size.comfortable")),
  };

  const tabletLength = cssLength(tablet);
  const desktopLength = cssLength(desktop);
  const tabletBelow = belowRem(tablet);
  const desktopBelow = belowRem(desktop);
  const frame = ".cu-app-shell__frame";

  const lines = [
    "/* Generated by @chameleon-ui/tokens. Do not edit. */",
    "/* Density ladder switching: mobile=comfortable, tablet=standard, desktop=compact. */",
    `/* Breakpoint lengths derive from breakpoint.tablet (${tabletLength}) and breakpoint.desktop (${desktopLength}). */`,
    "/* Explicit override: <html data-density=\"compact|standard|comfortable\"> wins over the media defaults. */",
    `/* Named container ${APP_SHELL_CONTAINER}: a narrow shell inside a wide viewport still gets phone density. */`,
    "",
    `@media (max-width: ${tabletBelow}) {`,
    "  :root {",
    `    --cu-density-active: ${scale.comfortable};`,
    `    --cu-control-size-active: ${size.comfortable};`,
    "  }",
    "}",
    "",
    `@media (min-width: ${desktopLength}) {`,
    "  :root {",
    `    --cu-density-active: ${scale.compact};`,
    `    --cu-control-size-active: ${size.compact};`,
    "  }",
    "}",
    "",
    `@container ${APP_SHELL_CONTAINER} (max-width: ${tabletBelow}) {`,
    `  ${frame} {`,
    `    --cu-density-active: ${scale.comfortable};`,
    `    --cu-control-size-active: ${size.comfortable};`,
    "  }",
    "}",
    "",
    `@container ${APP_SHELL_CONTAINER} (min-width: ${tabletLength}) and (max-width: ${desktopBelow}) {`,
    `  ${frame} {`,
    `    --cu-density-active: ${scale.standard};`,
    `    --cu-control-size-active: ${size.standard};`,
    "  }",
    "}",
    "",
    `@container ${APP_SHELL_CONTAINER} (min-width: ${desktopLength}) {`,
    `  ${frame} {`,
    `    --cu-density-active: ${scale.compact};`,
    `    --cu-control-size-active: ${size.compact};`,
    "  }",
    "}",
    "",
    "[data-density='compact'],",
    `[data-density='compact'] ${frame} {`,
    `  --cu-density-active: ${scale.compact};`,
    `  --cu-control-size-active: ${size.compact};`,
    "}",
    "",
    "[data-density='standard'],",
    `[data-density='standard'] ${frame} {`,
    `  --cu-density-active: ${scale.standard};`,
    `  --cu-control-size-active: ${size.standard};`,
    "}",
    "",
    "[data-density='comfortable'],",
    `[data-density='comfortable'] ${frame} {`,
    `  --cu-density-active: ${scale.comfortable};`,
    `  --cu-control-size-active: ${size.comfortable};`,
    "}",
    "",
  ];
  return lines.join("\n");
}
