/**
 * phase9:gates — hardening checks that do not publish npm or invent scores.
 *
 * - Lighthouse artifact exists and is either measured (with tool metadata) or
 *   explicit unmeasured (with a reason). Invented scores fail.
 * - VPAT file exists; draft is allowed; certified/signed claims without negation fail.
 * - Locale gap table exists (zero-gap is NOT required).
 * - publish:check dry run only.
 */
import { access, readFile } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const repoRoot = join(root, '..')

function fail(message) {
  console.error(`phase9:gates failed: ${message}`)
  process.exitCode = 1
}

function ok(message) {
  console.log(`[P9 ok] ${message}`)
}

async function exists(target) {
  try {
    await access(target)
    return true
  } catch {
    return false
  }
}

function runPnpm(args) {
  return new Promise((resolve, reject) => {
    const child = spawn('corepack', ['pnpm@9.15.0', ...args], {
      cwd: root,
      stdio: 'inherit',
      shell: true,
      env: process.env,
    })
    child.on('error', reject)
    child.on('exit', (code) => {
      if (code === 0) resolve()
      else reject(new Error(`corepack pnpm@9.15.0 ${args.join(' ')} exited ${code}`))
    })
  })
}

async function checkLighthouseArtifact() {
  const latest = join(root, 'benchmarks/reports/lhci-latest.json')
  const md = join(repoRoot, 'docs/project/reports/Phase-9-Lighthouse-R1-R3.md')
  if (!(await exists(latest))) {
    return fail('missing benchmarks/reports/lhci-latest.json — run `pnpm perf:lhci` (or leave an explicit unmeasured artifact)')
  }
  if (!(await exists(md))) {
    return fail('missing docs/project/reports/Phase-9-Lighthouse-R1-R3.md (must be generated by perf:lhci)')
  }

  let artifact
  try {
    artifact = JSON.parse(await readFile(latest, 'utf8'))
  } catch {
    return fail('lhci-latest.json is not valid JSON')
  }

  if (artifact.honesty?.invented === true) {
    return fail('lhci artifact must not set honesty.invented=true')
  }
  if (artifact.tool !== 'lighthouse') {
    return fail('lhci artifact tool must be lighthouse')
  }
  if (!artifact.generatedAt) return fail('lhci artifact missing generatedAt')
  if (artifact.status !== 'measured' && artifact.status !== 'unmeasured') {
    return fail('lhci artifact status must be measured or unmeasured')
  }

  const mdText = await readFile(md, 'utf8')
  if (!mdText.includes('禁止手写分数')) {
    return fail('Phase-9 Lighthouse markdown must remain a generated report (禁止手写分数)')
  }

  if (artifact.status === 'unmeasured') {
    if (!artifact.unmeasuredReason || String(artifact.unmeasuredReason).trim().length < 8) {
      return fail('unmeasured artifact must include a real unmeasuredReason')
    }
    for (const id of ['R1', 'R2', 'R3']) {
      const row = artifact.metrics?.[id]
      if (!row) return fail(`unmeasured artifact missing metrics.${id}`)
      if (row.status === 'measured') {
        return fail(`unmeasured artifact must not mark ${id} measured`)
      }
      if (row.valueMs != null || (id === 'R3' && row.value != null)) {
        return fail(`unmeasured artifact must not carry numeric ${id} (invented scores)`)
      }
    }
    if (!mdText.includes('未测') && !mdText.toLowerCase().includes('unmeasured')) {
      return fail('unmeasured markdown must say 未测 / unmeasured')
    }
    ok(`Lighthouse artifact present (explicit unmeasured): ${artifact.unmeasuredReason}`)
    return
  }

  if (!artifact.extra?.lighthouseVersion) {
    return fail('measured artifact must record extra.lighthouseVersion from a real Lighthouse run')
  }
  if (!artifact.url) return fail('measured artifact missing url')
  if (!artifact.throttling) return fail('measured artifact missing throttling 口径')
  if (artifact.honesty?.physicalMidTierAndroid === true) {
    return fail('do not claim a physical mid-tier Android device for this lab stand-in')
  }

  const r1 = artifact.metrics?.R1
  const r3 = artifact.metrics?.R3
  if (r1?.status === 'measured') {
    if (typeof r1.valueMs !== 'number' || !Number.isFinite(r1.valueMs) || r1.valueMs < 0) {
      return fail('measured R1 must be a finite LCP ms from Lighthouse')
    }
    if (!mdText.includes(String(r1.valueMs))) {
      return fail('markdown R1 ms must match lhci-latest.json (do not hand-edit)')
    }
  } else if (r1?.valueMs != null) {
    return fail('R1 numeric value present but status is not measured')
  }

  if (r3?.status === 'measured') {
    if (typeof r3.value !== 'number' || !Number.isFinite(r3.value) || r3.value < 0) {
      return fail('measured R3 must be a finite CLS from Lighthouse')
    }
  } else if (r3?.value != null) {
    return fail('R3 numeric value present but status is not measured')
  }

  const r2 = artifact.metrics?.R2
  if (r2?.status === 'measured') {
    if (typeof r2.valueMs !== 'number' || !Number.isFinite(r2.valueMs)) {
      return fail('measured R2 must be a finite INP ms from Lighthouse')
    }
  } else if (r2?.valueMs != null) {
    return fail('R2 numeric value present but status is not measured — do not substitute TBT')
  }

  ok(
    `Lighthouse artifact measured (LCP=${r1?.status === 'measured' ? `${r1.valueMs}ms` : 'unmeasured'}, INP=${r2?.status === 'measured' ? `${r2.valueMs}ms` : 'unmeasured'}, CLS=${r3?.status === 'measured' ? r3.value : 'unmeasured'}; lh=${artifact.extra.lighthouseVersion})`,
  )
}

async function checkVpat() {
  const mdPath = join(root, 'apps/docs/static/compliance/VPAT-ChameleonUI-v0.0.0.md')
  const pdfNamed = join(root, 'apps/docs/static/compliance/VPAT-ChameleonUI-v0.0.0.pdf.md')
  for (const file of [mdPath, pdfNamed]) {
    if (!(await exists(file))) fail(`VPAT missing ${file}`)
  }
  const text = await readFile(mdPath, 'utf8')
  const declaredDraft = /\*\*status=draft\*\*/.test(text) || /^status=draft$/m.test(text)
  const declaredPublished = /\*\*status=published\*\*/.test(text)
  if (!declaredDraft && !declaredPublished) {
    return fail('VPAT must declare **status=draft** or **status=published**')
  }
  if (declaredPublished && declaredDraft) {
    return fail('VPAT must not declare both **status=draft** and **status=published**')
  }
  if (/\bcertified\b/i.test(text) && !/not certified/i.test(text)) {
    return fail('VPAT must not present itself as certified')
  }
  if (/\blegally signed\b/i.test(text) && !/not legally signed/i.test(text)) {
    return fail('VPAT must not present itself as legally signed')
  }
  if (declaredPublished) {
    ok('VPAT artifact present (**status=published** — still must say not certified)')
  } else {
    ok('VPAT artifact present (**status=draft**; not certified)')
  }
}

async function checkGapTable() {
  const gap = join(root, 'apps/docs/static/compliance/locale-gap-table.json')
  if (!(await exists(gap))) fail('locale gap table missing')
  const table = JSON.parse(await readFile(gap, 'utf8'))
  if (typeof table.gapCount !== 'number') fail('gap table missing gapCount')
  ok(`locale gap table present (gapCount=${table.gapCount}; zero-gap not required for this gate)`)
}

async function checkPublishDry() {
  await runPnpm(['publish:check'])
  ok('publish:check dry run (npm publish not executed)')
}

async function main() {
  console.log('\n[phase9:gates] lighthouse artifact (measured or explicit unmeasured)')
  await checkLighthouseArtifact()
  if (process.exitCode) return

  console.log('\n[phase9:gates] VPAT file')
  await checkVpat()
  if (process.exitCode) return

  console.log('\n[phase9:gates] locale gap table exists')
  await checkGapTable()
  if (process.exitCode) return

  console.log('\n[phase9:gates] publish:check (dry)')
  await checkPublishDry()
  if (process.exitCode) return

  console.log(
    JSON.stringify(
      {
        ok: true,
        gates: [
          'lhci-artifact-measured-or-unmeasured',
          'vpat-file',
          'locale-gap-table',
          'publish-check-dry',
        ],
        note: 'Phase 9 hardening gates. Does not npm publish, does not require VPAT certified, does not invent Lighthouse scores, does not require 21-locale gap zero.',
      },
      null,
      2,
    ),
  )
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
})
